############################################################################
# Copyright (C) 2024 Nand Compute LLC | All Rights Reserved
#
############################################################################

LIB_NAME := axis_bgr888_to_rgb565

# Files for synthesis
SYN_FILES := axis_bgr888_to_rgb565.vhd

# Xilinx files for synthesis
SYN_FILES += axis_bgr888_to_rgb565_ip.tcl

include ../scripts/library.mk
