############################################################################
# Copyright (C) 2024 Nand Compute LLC | All Rights Reserved
#
############################################################################

LIB_NAME := axis_frame_sync

# Files for synthesis
SYN_FILES := axis_frame_sync.vhd

# Xilinx files for synthesis
SYN_FILES += axis_frame_sync_ip.tcl

include ../scripts/library.mk
