############################################################################
# Copyright (C) 2024 Nand Compute LLC | All Rights Reserved
#
############################################################################

LIB_NAME := axi_af_st7735

# Files for synthesis
SYN_FILES := axi_af_st7735.vhd
SYN_FILES += axi_lite_register_interface.vhd
SYN_FILES += spi_controller.vhd
SYN_FILES += ../common/nand_compute_std.vhd

# Xilinx files for synthesis
SYN_FILES += axi_af_st7735_ip.tcl

include ../scripts/library.mk
